fear(server/setup): converting qb evidence
overextended/ox_inventory pull request #1229
Opened 2023-03-28 06:43 UTC by Manason

fixes #1224 

new function convertQbItems could be called instead for the other conversions to reduce code duplication and improved to carry over more data. Will potentially take up improvements in subsequent PRs

2023-03-28 06:47 UTC, Manason commented on setup/convert.lua
> +			if Items(v?.name) and v.amount then
I kept the v.amount check from looking at the other examples in this file, but I'm not sure if it's possible for a qb item to have no amount.

2023-03-28 08:13 UTC, thelindat commented
https://github.com/overextended/ox_inventory/blob/main/modules/bridge/qb/server.lua#L178

2023-03-28 16:25 UTC, thelindat commented
> > https://github.com/overextended/ox_inventory/blob/main/modules/bridge/qb/server.lua#L178
> 
> We should extract a common function to convert items that isn't tied to a player and then refactor the convert code to call the bridge. I may do that in a separate PR.

Player is technically optional here; and used only for the sake of syncing physical accounts to items (money).

2023-03-29 12:00 UTC, Manason commented
Calling the bridge conversion function to handle the conversion now.

2023-03-30 19:33 UTC, thelindat requested changes

2023-03-30 19:33 UTC, thelindat commented on setup/convert.lua
> +			parameters[count] = { "INSERT INTO ox_inventory (owner, name, data) VALUES ('', :name, :data) ON DUPLICATE KEY UPDATE name = :name, data = :data", {
```lua
"INSERT INTO ox_inventory (owner, name, data) VALUES ('', ?, ?) ON DUPLICATE KEY UPDATE name = VALUES(name), data = VALUES(data)"
```

2023-03-31 06:04 UTC, merged